"use client"

import { useState } from "react"
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query"
import { PPICService } from "@/features/projects/services/ppic-service"
import { Loader2, Upload, FileText, Download, CheckCircle2, AlertCircle } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { toast } from "sonner"
import { Badge } from "@/components/ui/badge"
import Link from "next/link"

interface DokubahWidgetProps {
    projectId: number;
}

export function DokubahWidget({ projectId }: DokubahWidgetProps) {
    const queryClient = useQueryClient();
    const [file, setFile] = useState<File | null>(null);

    // 1. Fetch Dokubah Data
    const { data: dokubahData, isLoading } = useQuery({
        queryKey: ["dokubah", projectId],
        queryFn: () => PPICService.getDokubah(projectId)
    });

    // 2. Upload Mutation
    const uploadMutation = useMutation({
        mutationFn: async () => {
            if (!file) throw new Error("Please select a file first");
            return await PPICService.uploadDokubah(projectId, file);
        },
        onSuccess: () => {
            toast.success("Dokubah uploaded successfully");
            setFile(null);
            queryClient.invalidateQueries({ queryKey: ["dokubah", projectId] });
        },
        onError: (error: any) => {
            toast.error(error.message || "Failed to upload Dokubah");
        }
    });

    const status = dokubahData?.data?.dokubah_status || 'not_uploaded';
    const fileUrl = dokubahData?.data?.file_url;

    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files[0]) {
            setFile(e.target.files[0]);
        }
    };

    if (isLoading) {
        return (
            <div className="flex items-center justify-center p-8 border rounded-lg bg-neutral-50">
                <Loader2 className="h-6 w-6 animate-spin text-neutral-400" />
            </div>
        )
    }

    return (
        <Card className="border-neutral-200 shadow-sm h-full">
            <CardHeader className="bg-neutral-50/50 border-b border-neutral-100 pb-4">
                <div className="flex justify-between items-center">
                    <CardTitle className="text-sm font-bold uppercase tracking-wide text-neutral-500 flex items-center gap-2">
                        <FileText className="h-4 w-4" />
                        Dokubah (Material List)
                    </CardTitle>
                    <Badge variant={status === 'not_uploaded' ? 'outline' : 'default'} className={
                        status === 'uploaded' ? 'bg-green-600 hover:bg-green-700' :
                            status === 'revised' ? 'bg-blue-600 hover:bg-blue-700' : ''
                    }>
                        {status === 'not_uploaded' ? 'Pending' : status === 'revised' ? 'Revised' : 'Uploaded'}
                    </Badge>
                </div>
                <CardDescription>
                    Material list generated by PPIC.
                </CardDescription>
            </CardHeader>
            <CardContent className="p-6 space-y-6">

                {/* 1. PDF Viewer (if available) */}
                {fileUrl && (
                    <div className="space-y-3">
                        <div className="flex items-center justify-between">
                            <div className="flex items-center gap-2">
                                <CheckCircle2 className="h-4 w-4 text-green-600" />
                                <p className="text-sm font-semibold text-neutral-900">Dokubah Available</p>
                            </div>
                            <Link href={fileUrl} target="_blank">
                                <Button size="sm" variant="outline" className="border-green-200 text-green-700 hover:bg-green-100">
                                    <Download className="mr-2 h-3 w-3" /> Download
                                </Button>
                            </Link>
                        </div>

                        {/* PDF Viewer */}
                        <div className="border border-neutral-200 rounded-lg overflow-hidden bg-neutral-50">
                            <iframe
                                src={fileUrl}
                                className="w-full h-[600px]"
                                title="Dokubah PDF Viewer"
                            />
                        </div>
                    </div>
                )}

                {/* No file state */}
                {!fileUrl && (
                    <div className="bg-neutral-50 border border-neutral-100 rounded-lg p-4 flex items-center gap-3">
                        <div className="bg-white p-2 rounded-full border border-neutral-200 shadow-sm">
                            <AlertCircle className="h-5 w-5 text-neutral-400" />
                        </div>
                        <div>
                            <p className="text-sm font-medium text-neutral-900">No Dokubah yet</p>
                            <p className="text-xs text-neutral-500">Please upload using the form below.</p>
                        </div>
                    </div>
                )}

                {/* 2. Upload Form */}
                <div className="space-y-3 pt-2 border-t border-neutral-100">
                    <label className="text-xs font-semibold text-neutral-500 uppercase">Update / Upload New</label>
                    <div className="flex gap-2">
                        <input
                            type="file"
                            accept=".pdf,.xlsx,.xls,.doc,.docx"
                            onChange={handleFileChange}
                            className="block w-full text-sm text-neutral-500
                                file:mr-4 file:py-2 file:px-4
                                file:rounded-md file:border-0
                                file:text-xs file:font-semibold
                                file:bg-orange-50 file:text-orange-700
                                hover:file:bg-orange-100
                                border border-neutral-200 rounded-md cursor-pointer
                            "
                        />
                        <Button
                            size="sm"
                            onClick={() => uploadMutation.mutate()}
                            disabled={!file || uploadMutation.isPending}
                        >
                            {uploadMutation.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Upload className="h-4 w-4" />}
                        </Button>
                    </div>
                    <p className="text-[10px] text-neutral-400">Supported: PDF, Excel, Word (Max 15MB)</p>
                </div>

            </CardContent>
        </Card>
    )
}
